version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: PlacePrep-postgres
    restart: always
    environment:
      POSTGRES_DB: PlacePrep
      POSTGRES_USER: vraj
      POSTGRES_PASSWORD: vraj_2006
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 30s
      retries: 5
    volumes:
      - ./data/db:/var/lib/postgresql/data
    attach: false

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pepa-linha-dark
    ports:
      - 8080:8080
    depends_on:
      - db
